/**
 * Profiles — multiple isolated identities for a single provider.
 *
 * A "profile" is an isolated config/identity directory the provider's runtime
 * can be pointed at via an env var (Claude `CLAUDE_CONFIG_DIR`, Codex
 * `CODEX_HOME`, Gemini `GEMINI_CONFIG_DIR`, …). Two profiles = two distinct
 * accounts / login states / agent customizations / history sets, all running
 * the same provider binary.
 *
 * The user-facing scenario this exists for: an employee with separate
 * "claude-personal" and "claude-work" shell aliases that point CLAUDE_CONFIG_DIR
 * at different folders. The host turns that into a first-class concept —
 * choosable per session, with a default per workspace-agent slot — instead of
 * making the user re-shell their alias every time they switch context.
 *
 * Provider opts in by:
 *   - declaring `capabilities.profiles = true`
 *   - implementing `JackProvider.profiles` with a {@link ProfilesApi}
 *   - injecting the right env var inside `applyProfile`
 *
 * Storage of the profile *list* lives on the host's per-provider kv (provider
 * stores it via `host.kv` at activation time). Storage of the profile
 * *content* (auth, sessions, agents, history) lives inside `configDir` on
 * disk and is the runtime's concern, not the host's — Jack never reads or
 * writes inside `configDir`.
 */

import type { AgentQueryOptions } from './backend'

/**
 * One profile entry. `id` is host-generated and stable; the human edits
 * `label` + `configDir` freely.
 *
 * `isDefault` is exclusive within a provider — exactly one profile carries
 * the flag at any time. Provider implementations enforce that invariant in
 * `update`/`create` (when `setDefault` is true, demote the previous default).
 */
export type ProviderProfile = {
  /** Stable identifier — host-generated UUID; never edited by user. */
  id: string
  /** User-facing display label ("Work", "Personal", …). */
  label: string
  /** Absolute path to the runtime config dir on the host filesystem. */
  configDir: string
  /** Exactly one profile per provider carries this flag. */
  isDefault: boolean
  /** ISO 8601 — when the profile was first created in Jack's registry. */
  createdAt: string
}

/**
 * Result of {@link ProfilesApi.probeProfile} — best-effort introspection of
 * what's already stored under `configDir` so the UI can show the user
 * "Connected as <X>" instead of an opaque path.
 *
 * Provider populates whichever fields it can read cheaply (no network
 * round-trips) — fields it can't infer stay undefined.
 */
export type ProviderProfileProbe = {
  /** True when the dir exists and looks like a valid runtime config. */
  exists: boolean
  /** True when the dir contains usable credentials. Tri-state: false = present-but-invalid, undefined = N/A. */
  authenticated?: boolean
  /** Human-readable identity hint (email, account label) when discoverable. */
  accountLabel?: string
}

/**
 * Input shape for {@link ProfilesApi.create}. The `id` is host-generated by
 * the provider implementation (typically `crypto.randomUUID()`); the caller
 * supplies the human bits.
 */
export type CreateProfileInput = {
  label: string
  configDir: string
  /** When true, the new profile becomes the default (demotes previous default). */
  setDefault?: boolean
}

/**
 * Provider-owned profiles capability. Optional on {@link JackProvider} —
 * absent = the provider's runtime always uses its implicit default config dir
 * and the host hides every profiles-related affordance.
 */
export type ProfilesApi = {
  /**
   * Enumerate the registered profiles in stable order. Provider MUST seed
   * a "Default" profile pointing at its implicit config dir on first call
   * (lazy migration — preserves the user's existing setup without manual
   * intervention).
   */
  list(): Promise<ProviderProfile[]>

  /**
   * Register a new profile. Provider generates the `id` and persists the
   * row. Returns the freshly-created profile so the caller doesn't have to
   * round-trip through `list()`.
   */
  create(input: CreateProfileInput): Promise<ProviderProfile>

  /**
   * Patch an existing profile. Empty patch = no-op. Setting `isDefault: true`
   * demotes whichever profile currently holds the default flag.
   */
  update(
    id: string,
    patch: Partial<Pick<ProviderProfile, 'label' | 'configDir' | 'isDefault'>>
  ): Promise<ProviderProfile>

  /**
   * Remove a profile by id. MUST refuse to remove the last remaining profile
   * (the provider always needs a default to fall back to). MUST refuse to
   * remove the default profile when other profiles exist — caller has to
   * promote a replacement first.
   *
   * Note: this only removes the registry entry. Files inside `configDir`
   * stay on disk untouched — destructive cleanup is the user's responsibility
   * (we never `rm -rf` a directory the user gave us).
   */
  remove(id: string): Promise<void>

  /**
   * Mutate spawn options in place to point the runtime at the chosen
   * profile's `configDir`. Each provider injects its native env var
   * (Claude: `CLAUDE_CONFIG_DIR`; Codex: `CODEX_HOME`; …) and any other
   * spawn-time wiring the runtime needs.
   *
   * Called once per spawn by the host, after `applyKnowledgeContext` and
   * `prepareSpawnOptions`. Unknown `profileId` MUST be a silent no-op
   * (caller falls back to the implicit default behavior).
   */
  applyProfile(options: AgentQueryOptions, profileId: string): Promise<void>

  /**
   * Best-effort introspection of what's stored under `configDir` so the
   * UI can show "Connected as X" / "Empty profile" hints. Provider returns
   * what it can read cheaply (file presence, parsed credentials file) —
   * no network calls. Optional: providers that can't introspect their
   * own config dir omit this and the UI falls back to a path-only display.
   */
  probeProfile?(configDir: string): Promise<ProviderProfileProbe>
}
